//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use super::sea_orm_active_enums::Regions;
use super::sea_orm_active_enums::RelicRefinement;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "lobbies")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub expiry: DateTime,
    pub region: Regions,
    pub refinement: RelicRefinement,
    pub activity: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_lobbies::Entity")]
    UsersLobbies,
}

impl Related<super::users_lobbies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersLobbies.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_lobbies::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_lobbies::Relation::Lobbies.def().rev())
    }
}
