[package]
name = "module"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { version = "2.0.3", features = ["unstable"] }
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
http = "1.4.0"
bitmask-enum = "2.2.5"

[lints.clippy]
"missing_errors_doc" = "allow"
"pedantic" = { level = "warn", priority = -1 }
