// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateLobbyReducer from "../create_lobby_reducer";
import SetUsernameReducer from "../set_username_reducer";
import SetWarframeIdReducer from "../set_warframe_id_reducer";

export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type SetWarframeIdParams = __Infer<typeof SetWarframeIdReducer>;

