// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddDummyReducer from "../add_dummy_reducer";
import BanReducer from "../ban_reducer";
import CreateOrUpdateLobbyReducer from "../create_or_update_lobby_reducer";
import DeleteMyAccountReducer from "../delete_my_account_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import KickReducer from "../kick_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import RemoveDummyReducer from "../remove_dummy_reducer";
import SetUsernameReducer from "../set_username_reducer";
import SetWarframeIdReducer from "../set_warframe_id_reducer";

export type AddDummyParams = __Infer<typeof AddDummyReducer>;
export type BanParams = __Infer<typeof BanReducer>;
export type CreateOrUpdateLobbyParams = __Infer<typeof CreateOrUpdateLobbyReducer>;
export type DeleteMyAccountParams = __Infer<typeof DeleteMyAccountReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type KickParams = __Infer<typeof KickReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type RemoveDummyParams = __Infer<typeof RemoveDummyReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type SetWarframeIdParams = __Infer<typeof SetWarframeIdReducer>;

