// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateOrUpdateLobbyReducer from "../create_or_update_lobby_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import SetUsernameReducer from "../set_username_reducer";
import SetWarframeIdReducer from "../set_warframe_id_reducer";

export type CreateOrUpdateLobbyParams = __Infer<typeof CreateOrUpdateLobbyReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type SetWarframeIdParams = __Infer<typeof SetWarframeIdReducer>;

