// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Region,
  RelicRefinement,
  RotationType,
} from "./types";


export default __t.row({
  host: __t.identity().primaryKey(),
  created: __t.timestamp(),
  lobbySize: __t.u8().name("lobby_size"),
  get region() {
    return Region;
  },
  get refinement() {
    return RelicRefinement;
  },
  activity: __t.string(),
  get rotationType() {
    return RotationType.name("rotation_type");
  },
  amountPlayers: __t.u8().name("amount_players"),
  dummies: __t.u8(),
});
