// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AllowList = __t.object("AllowList", {
  id: __t.identity(),
});
export type AllowList = __Infer<typeof AllowList>;

export const DisconnectTimer = __t.object("DisconnectTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  userId: __t.u32(),
});
export type DisconnectTimer = __Infer<typeof DisconnectTimer>;

export const Lobby = __t.object("Lobby", {
  lobbyId: __t.u32(),
  created: __t.timestamp(),
  lobbySize: __t.u8(),
  get region() {
    return Region;
  },
  get refinement() {
    return RelicRefinement;
  },
  activity: __t.string(),
  get rotationType() {
    return RotationType;
  },
  amountPlayers: __t.u8(),
  dummies: __t.u8(),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbyBan = __t.object("LobbyBan", {
  lobbyId: __t.u32(),
  userId: __t.u32(),
});
export type LobbyBan = __Infer<typeof LobbyBan>;

export const LobbyJoin = __t.object("LobbyJoin", {
  userId: __t.u32(),
  lobbyId: __t.u32(),
});
export type LobbyJoin = __Infer<typeof LobbyJoin>;

export const Me = __t.object("Me", {
  get user() {
    return User;
  },
  get details() {
    return UserDetails;
  },
});
export type Me = __Infer<typeof Me>;

export const OldUser = __t.object("OldUser", {
  id: __t.identity(),
  username: __t.string(),
  verified: __t.bool(),
});
export type OldUser = __Infer<typeof OldUser>;

export const Permissions = __t.object("Permissions", {
  bits: __t.u128(),
});
export type Permissions = __Infer<typeof Permissions>;

// The tagged union or sum type for the algebraic type `Region`.
export const Region = __t.enum("Region", {
  As: __t.unit(),
  Eer: __t.unit(),
  Eu: __t.unit(),
  Na: __t.unit(),
  Oc: __t.unit(),
  Sa: __t.unit(),
});
export type Region = __Infer<typeof Region>;

export const Relic = __t.object("Relic", {
  relic: __t.string(),
});
export type Relic = __Infer<typeof Relic>;

// The tagged union or sum type for the algebraic type `RelicRefinement`.
export const RelicRefinement = __t.enum("RelicRefinement", {
  Intact: __t.unit(),
  Exceptional: __t.unit(),
  Flawless: __t.unit(),
  Radiant: __t.unit(),
});
export type RelicRefinement = __Infer<typeof RelicRefinement>;

export const RelicTimer = __t.object("RelicTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type RelicTimer = __Infer<typeof RelicTimer>;

// The tagged union or sum type for the algebraic type `RotationType`.
export const RotationType = __t.enum("RotationType", {
  TwoATwoB: __t.unit(),
  FourA: __t.unit(),
});
export type RotationType = __Infer<typeof RotationType>;

export const User = __t.object("User", {
  id: __t.u32(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

export const UserDetails = __t.object("UserDetails", {
  userId: __t.u32(),
  get flags() {
    return UserFlags;
  },
  get permissions() {
    return Permissions;
  },
});
export type UserDetails = __Infer<typeof UserDetails>;

export const UserFlags = __t.object("UserFlags", {
  bits: __t.u64(),
});
export type UserFlags = __Infer<typeof UserFlags>;

export const UserId = __t.object("UserId", {
  identity: __t.identity(),
  id: __t.u32(),
});
export type UserId = __Infer<typeof UserId>;

export const VerifyTimer = __t.object("VerifyTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  userId: __t.u32(),
  warframeId: __t.string(),
  code: __t.string(),
  attempts: __t.u8(),
});
export type VerifyTimer = __Infer<typeof VerifyTimer>;

