// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddDummyArgs {}

impl From<AddDummyArgs> for super::Reducer {
    fn from(args: AddDummyArgs) -> Self {
        Self::AddDummy
    }
}

impl __sdk::InModule for AddDummyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_dummy`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_dummy {
    /// Request that the remote module invoke the reducer `add_dummy` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_dummy:add_dummy_then`] to run a callback after the reducer completes.
    fn add_dummy(&self) -> __sdk::Result<()> {
        self.add_dummy_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_dummy` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_dummy_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_dummy for super::RemoteReducers {
    fn add_dummy_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AddDummyArgs {}, callback)
    }
}
