// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::allow_list_type::AllowList;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `allowlist`.
///
/// Obtain a handle from the [`AllowlistTableAccess::allowlist`] method on [`super::RemoteTables`],
/// like `ctx.db.allowlist()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.allowlist().on_insert(...)`.
pub struct AllowlistTableHandle<'ctx> {
    imp: __sdk::TableHandle<AllowList>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `allowlist`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AllowlistTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AllowlistTableHandle`], which mediates access to the table `allowlist`.
    fn allowlist(&self) -> AllowlistTableHandle<'_>;
}

impl AllowlistTableAccess for super::RemoteTables {
    fn allowlist(&self) -> AllowlistTableHandle<'_> {
        AllowlistTableHandle {
            imp: self.imp.get_table::<AllowList>("allowlist"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AllowlistInsertCallbackId(__sdk::CallbackId);
pub struct AllowlistDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AllowlistTableHandle<'ctx> {
    type Row = AllowList;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AllowList> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AllowlistInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllowlistInsertCallbackId {
        AllowlistInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllowlistInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AllowlistDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllowlistDeleteCallbackId {
        AllowlistDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllowlistDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AllowlistUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AllowlistTableHandle<'ctx> {
    type UpdateCallbackId = AllowlistUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AllowlistUpdateCallbackId {
        AllowlistUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AllowlistUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `allowlist`,
/// which allows point queries on the field of the same name
/// via the [`AllowlistIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.allowlist().id().find(...)`.
pub struct AllowlistIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AllowList, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AllowlistTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `allowlist`.
    pub fn id(&self) -> AllowlistIdUnique<'ctx> {
        AllowlistIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AllowlistIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<AllowList> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AllowList>("allowlist");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AllowList>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AllowList>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AllowList`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait allowlistQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AllowList`.
    fn allowlist(&self) -> __sdk::__query_builder::Table<AllowList>;
}

impl allowlistQueryTableAccess for __sdk::QueryTableAccessor {
    fn allowlist(&self) -> __sdk::__query_builder::Table<AllowList> {
        __sdk::__query_builder::Table::new("allowlist")
    }
}
