// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AllowList {
    pub id: __sdk::Identity,
}

impl __sdk::InModule for AllowList {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AllowList`.
///
/// Provides typed access to columns for query building.
pub struct AllowListCols {
    pub id: __sdk::__query_builder::Col<AllowList, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for AllowList {
    type Cols = AllowListCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AllowListCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
        }
    }
}

/// Indexed column accessor struct for the table `AllowList`.
///
/// Provides typed access to indexed columns for query building.
pub struct AllowListIxCols {
    pub id: __sdk::__query_builder::IxCol<AllowList, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AllowList {
    type IxCols = AllowListIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AllowListIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AllowList {}
