// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::region_type::Region;
use super::relic_refinement_type::RelicRefinement;
use super::rotation_type_type::RotationType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateOrUpdateLobbyArgs {
    pub lobby_size: u8,
    pub region: Region,
    pub refinement: RelicRefinement,
    pub rotation_type: RotationType,
    pub activity: String,
}

impl From<CreateOrUpdateLobbyArgs> for super::Reducer {
    fn from(args: CreateOrUpdateLobbyArgs) -> Self {
        Self::CreateOrUpdateLobby {
            lobby_size: args.lobby_size,
            region: args.region,
            refinement: args.refinement,
            rotation_type: args.rotation_type,
            activity: args.activity,
        }
    }
}

impl __sdk::InModule for CreateOrUpdateLobbyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_or_update_lobby`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_or_update_lobby {
    /// Request that the remote module invoke the reducer `create_or_update_lobby` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_or_update_lobby:create_or_update_lobby_then`] to run a callback after the reducer completes.
    fn create_or_update_lobby(
        &self,
        lobby_size: u8,
        region: Region,
        refinement: RelicRefinement,
        rotation_type: RotationType,
        activity: String,
    ) -> __sdk::Result<()> {
        self.create_or_update_lobby_then(
            lobby_size,
            region,
            refinement,
            rotation_type,
            activity,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_or_update_lobby` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_or_update_lobby_then(
        &self,
        lobby_size: u8,
        region: Region,
        refinement: RelicRefinement,
        rotation_type: RotationType,
        activity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_or_update_lobby for super::RemoteReducers {
    fn create_or_update_lobby_then(
        &self,
        lobby_size: u8,
        region: Region,
        refinement: RelicRefinement,
        rotation_type: RotationType,
        activity: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateOrUpdateLobbyArgs {
                lobby_size,
                region,
                refinement,
                rotation_type,
                activity,
            },
            callback,
        )
    }
}
