// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DisconnectTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub user_id: u32,
}

impl __sdk::InModule for DisconnectTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DisconnectTimer`.
///
/// Provides typed access to columns for query building.
pub struct DisconnectTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<DisconnectTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<DisconnectTimer, __sdk::ScheduleAt>,
    pub user_id: __sdk::__query_builder::Col<DisconnectTimer, u32>,
}

impl __sdk::__query_builder::HasCols for DisconnectTimer {
    type Cols = DisconnectTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DisconnectTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
        }
    }
}

/// Indexed column accessor struct for the table `DisconnectTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct DisconnectTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<DisconnectTimer, u64>,
    pub user_id: __sdk::__query_builder::IxCol<DisconnectTimer, u32>,
}

impl __sdk::__query_builder::HasIxCols for DisconnectTimer {
    type IxCols = DisconnectTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DisconnectTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DisconnectTimer {}
