// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::disconnect_timer_type::DisconnectTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `disconnect_timer`.
///
/// Obtain a handle from the [`DisconnectTimerTableAccess::disconnect_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.disconnect_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.disconnect_timer().on_insert(...)`.
pub struct DisconnectTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<DisconnectTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `disconnect_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DisconnectTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DisconnectTimerTableHandle`], which mediates access to the table `disconnect_timer`.
    fn disconnect_timer(&self) -> DisconnectTimerTableHandle<'_>;
}

impl DisconnectTimerTableAccess for super::RemoteTables {
    fn disconnect_timer(&self) -> DisconnectTimerTableHandle<'_> {
        DisconnectTimerTableHandle {
            imp: self.imp.get_table::<DisconnectTimer>("disconnect_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DisconnectTimerInsertCallbackId(__sdk::CallbackId);
pub struct DisconnectTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DisconnectTimerTableHandle<'ctx> {
    type Row = DisconnectTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DisconnectTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DisconnectTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DisconnectTimerInsertCallbackId {
        DisconnectTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DisconnectTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DisconnectTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DisconnectTimerDeleteCallbackId {
        DisconnectTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DisconnectTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct DisconnectTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DisconnectTimerTableHandle<'ctx> {
    type UpdateCallbackId = DisconnectTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DisconnectTimerUpdateCallbackId {
        DisconnectTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DisconnectTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `disconnect_timer`,
/// which allows point queries on the field of the same name
/// via the [`DisconnectTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.disconnect_timer().scheduled_id().find(...)`.
pub struct DisconnectTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DisconnectTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DisconnectTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `disconnect_timer`.
    pub fn scheduled_id(&self) -> DisconnectTimerScheduledIdUnique<'ctx> {
        DisconnectTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DisconnectTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DisconnectTimer> {
        self.imp.find(col_val)
    }
}

/// Access to the `user_id` unique index on the table `disconnect_timer`,
/// which allows point queries on the field of the same name
/// via the [`DisconnectTimerUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.disconnect_timer().user_id().find(...)`.
pub struct DisconnectTimerUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DisconnectTimer, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DisconnectTimerTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `disconnect_timer`.
    pub fn user_id(&self) -> DisconnectTimerUserIdUnique<'ctx> {
        DisconnectTimerUserIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DisconnectTimerUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<DisconnectTimer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DisconnectTimer>("disconnect_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
    _table.add_unique_constraint::<u32>("user_id", |row| &row.user_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DisconnectTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DisconnectTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DisconnectTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait disconnect_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DisconnectTimer`.
    fn disconnect_timer(&self) -> __sdk::__query_builder::Table<DisconnectTimer>;
}

impl disconnect_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn disconnect_timer(&self) -> __sdk::__query_builder::Table<DisconnectTimer> {
        __sdk::__query_builder::Table::new("disconnect_timer")
    }
}
