// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::disconnect_timer_type::DisconnectTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DisconnectArgs {
    pub disconnect_timer: DisconnectTimer,
}

impl From<DisconnectArgs> for super::Reducer {
    fn from(args: DisconnectArgs) -> Self {
        Self::Disconnect {
            disconnect_timer: args.disconnect_timer,
        }
    }
}

impl __sdk::InModule for DisconnectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `disconnect`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait disconnect {
    /// Request that the remote module invoke the reducer `disconnect` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`disconnect:disconnect_then`] to run a callback after the reducer completes.
    fn disconnect(&self, disconnect_timer: DisconnectTimer) -> __sdk::Result<()> {
        self.disconnect_then(disconnect_timer, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `disconnect` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn disconnect_then(
        &self,
        disconnect_timer: DisconnectTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl disconnect for super::RemoteReducers {
    fn disconnect_then(
        &self,
        disconnect_timer: DisconnectTimer,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DisconnectArgs { disconnect_timer }, callback)
    }
}
