// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct KickstartPermsArgs {
    pub target: __sdk::Identity,
}

impl From<KickstartPermsArgs> for super::Reducer {
    fn from(args: KickstartPermsArgs) -> Self {
        Self::KickstartPerms {
            target: args.target,
        }
    }
}

impl __sdk::InModule for KickstartPermsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `kickstart_perms`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait kickstart_perms {
    /// Request that the remote module invoke the reducer `kickstart_perms` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`kickstart_perms:kickstart_perms_then`] to run a callback after the reducer completes.
    fn kickstart_perms(&self, target: __sdk::Identity) -> __sdk::Result<()> {
        self.kickstart_perms_then(target, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `kickstart_perms` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn kickstart_perms_then(
        &self,
        target: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl kickstart_perms for super::RemoteReducers {
    fn kickstart_perms_then(
        &self,
        target: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(KickstartPermsArgs { target }, callback)
    }
}
