// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_join_type::LobbyJoin;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lobby_join`.
///
/// Obtain a handle from the [`LobbyJoinTableAccess::lobby_join`] method on [`super::RemoteTables`],
/// like `ctx.db.lobby_join()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_join().on_insert(...)`.
pub struct LobbyJoinTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbyJoin>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lobby_join`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LobbyJoinTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LobbyJoinTableHandle`], which mediates access to the table `lobby_join`.
    fn lobby_join(&self) -> LobbyJoinTableHandle<'_>;
}

impl LobbyJoinTableAccess for super::RemoteTables {
    fn lobby_join(&self) -> LobbyJoinTableHandle<'_> {
        LobbyJoinTableHandle {
            imp: self.imp.get_table::<LobbyJoin>("lobby_join"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LobbyJoinInsertCallbackId(__sdk::CallbackId);
pub struct LobbyJoinDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LobbyJoinTableHandle<'ctx> {
    type Row = LobbyJoin;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbyJoin> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LobbyJoinInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyJoinInsertCallbackId {
        LobbyJoinInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LobbyJoinInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LobbyJoinDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyJoinDeleteCallbackId {
        LobbyJoinDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LobbyJoinDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LobbyJoinUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LobbyJoinTableHandle<'ctx> {
    type UpdateCallbackId = LobbyJoinUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LobbyJoinUpdateCallbackId {
        LobbyJoinUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LobbyJoinUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `user_id` unique index on the table `lobby_join`,
/// which allows point queries on the field of the same name
/// via the [`LobbyJoinUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_join().user_id().find(...)`.
pub struct LobbyJoinUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LobbyJoin, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LobbyJoinTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `lobby_join`.
    pub fn user_id(&self) -> LobbyJoinUserIdUnique<'ctx> {
        LobbyJoinUserIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LobbyJoinUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<LobbyJoin> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbyJoin>("lobby_join");
    _table.add_unique_constraint::<u32>("user_id", |row| &row.user_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LobbyJoin>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbyJoin>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LobbyJoin`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait lobby_joinQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LobbyJoin`.
    fn lobby_join(&self) -> __sdk::__query_builder::Table<LobbyJoin>;
}

impl lobby_joinQueryTableAccess for __sdk::QueryTableAccessor {
    fn lobby_join(&self) -> __sdk::__query_builder::Table<LobbyJoin> {
        __sdk::__query_builder::Table::new("lobby_join")
    }
}
