// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyBan {
    pub lobby_id: u32,
    pub user_id: u32,
}

impl __sdk::InModule for LobbyBan {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LobbyBan`.
///
/// Provides typed access to columns for query building.
pub struct LobbyBanCols {
    pub lobby_id: __sdk::__query_builder::Col<LobbyBan, u32>,
    pub user_id: __sdk::__query_builder::Col<LobbyBan, u32>,
}

impl __sdk::__query_builder::HasCols for LobbyBan {
    type Cols = LobbyBanCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyBanCols {
            lobby_id: __sdk::__query_builder::Col::new(table_name, "lobby_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
        }
    }
}

/// Indexed column accessor struct for the table `LobbyBan`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyBanIxCols {
    pub lobby_id: __sdk::__query_builder::IxCol<LobbyBan, u32>,
    pub user_id: __sdk::__query_builder::IxCol<LobbyBan, u32>,
}

impl __sdk::__query_builder::HasIxCols for LobbyBan {
    type IxCols = LobbyBanIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyBanIxCols {
            lobby_id: __sdk::__query_builder::IxCol::new(table_name, "lobby_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LobbyBan {}
