// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_ban_type::LobbyBan;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `lobby_ban`.
///
/// Obtain a handle from the [`LobbyBanTableAccess::lobby_ban`] method on [`super::RemoteTables`],
/// like `ctx.db.lobby_ban()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.lobby_ban().on_insert(...)`.
pub struct LobbyBanTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbyBan>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `lobby_ban`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LobbyBanTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LobbyBanTableHandle`], which mediates access to the table `lobby_ban`.
    fn lobby_ban(&self) -> LobbyBanTableHandle<'_>;
}

impl LobbyBanTableAccess for super::RemoteTables {
    fn lobby_ban(&self) -> LobbyBanTableHandle<'_> {
        LobbyBanTableHandle {
            imp: self.imp.get_table::<LobbyBan>("lobby_ban"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LobbyBanInsertCallbackId(__sdk::CallbackId);
pub struct LobbyBanDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LobbyBanTableHandle<'ctx> {
    type Row = LobbyBan;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbyBan> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LobbyBanInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyBanInsertCallbackId {
        LobbyBanInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LobbyBanInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LobbyBanDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LobbyBanDeleteCallbackId {
        LobbyBanDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LobbyBanDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbyBan>("lobby_ban");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LobbyBan>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbyBan>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LobbyBan`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait lobby_banQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LobbyBan`.
    fn lobby_ban(&self) -> __sdk::__query_builder::Table<LobbyBan>;
}

impl lobby_banQueryTableAccess for __sdk::QueryTableAccessor {
    fn lobby_ban(&self) -> __sdk::__query_builder::Table<LobbyBan> {
        __sdk::__query_builder::Table::new("lobby_ban")
    }
}
