// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::region_type::Region;
use super::relic_refinement_type::RelicRefinement;
use super::rotation_type_type::RotationType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Lobby {
    pub lobby_id: u32,
    pub created: __sdk::Timestamp,
    pub lobby_size: u8,
    pub region: Region,
    pub refinement: RelicRefinement,
    pub activity: String,
    pub rotation_type: RotationType,
    pub amount_players: u8,
    pub dummies: u8,
}

impl __sdk::InModule for Lobby {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Lobby`.
///
/// Provides typed access to columns for query building.
pub struct LobbyCols {
    pub lobby_id: __sdk::__query_builder::Col<Lobby, u32>,
    pub created: __sdk::__query_builder::Col<Lobby, __sdk::Timestamp>,
    pub lobby_size: __sdk::__query_builder::Col<Lobby, u8>,
    pub region: __sdk::__query_builder::Col<Lobby, Region>,
    pub refinement: __sdk::__query_builder::Col<Lobby, RelicRefinement>,
    pub activity: __sdk::__query_builder::Col<Lobby, String>,
    pub rotation_type: __sdk::__query_builder::Col<Lobby, RotationType>,
    pub amount_players: __sdk::__query_builder::Col<Lobby, u8>,
    pub dummies: __sdk::__query_builder::Col<Lobby, u8>,
}

impl __sdk::__query_builder::HasCols for Lobby {
    type Cols = LobbyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyCols {
            lobby_id: __sdk::__query_builder::Col::new(table_name, "lobby_id"),
            created: __sdk::__query_builder::Col::new(table_name, "created"),
            lobby_size: __sdk::__query_builder::Col::new(table_name, "lobby_size"),
            region: __sdk::__query_builder::Col::new(table_name, "region"),
            refinement: __sdk::__query_builder::Col::new(table_name, "refinement"),
            activity: __sdk::__query_builder::Col::new(table_name, "activity"),
            rotation_type: __sdk::__query_builder::Col::new(table_name, "rotation_type"),
            amount_players: __sdk::__query_builder::Col::new(table_name, "amount_players"),
            dummies: __sdk::__query_builder::Col::new(table_name, "dummies"),
        }
    }
}

/// Indexed column accessor struct for the table `Lobby`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyIxCols {
    pub lobby_id: __sdk::__query_builder::IxCol<Lobby, u32>,
}

impl __sdk::__query_builder::HasIxCols for Lobby {
    type IxCols = LobbyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyIxCols {
            lobby_id: __sdk::__query_builder::IxCol::new(table_name, "lobby_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Lobby {}
