// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LobbyJoin {
    pub user_id: u32,
    pub lobby_id: u32,
}

impl __sdk::InModule for LobbyJoin {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LobbyJoin`.
///
/// Provides typed access to columns for query building.
pub struct LobbyJoinCols {
    pub user_id: __sdk::__query_builder::Col<LobbyJoin, u32>,
    pub lobby_id: __sdk::__query_builder::Col<LobbyJoin, u32>,
}

impl __sdk::__query_builder::HasCols for LobbyJoin {
    type Cols = LobbyJoinCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyJoinCols {
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            lobby_id: __sdk::__query_builder::Col::new(table_name, "lobby_id"),
        }
    }
}

/// Indexed column accessor struct for the table `LobbyJoin`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyJoinIxCols {
    pub lobby_id: __sdk::__query_builder::IxCol<LobbyJoin, u32>,
    pub user_id: __sdk::__query_builder::IxCol<LobbyJoin, u32>,
}

impl __sdk::__query_builder::HasIxCols for LobbyJoin {
    type IxCols = LobbyJoinIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyJoinIxCols {
            lobby_id: __sdk::__query_builder::IxCol::new(table_name, "lobby_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LobbyJoin {}
