// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::me_type::Me;
use super::user_details_type::UserDetails;
use super::user_type::User;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `me`.
///
/// Obtain a handle from the [`MeTableAccess::me`] method on [`super::RemoteTables`],
/// like `ctx.db.me()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.me().on_insert(...)`.
pub struct MeTableHandle<'ctx> {
    imp: __sdk::TableHandle<Me>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `me`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MeTableHandle`], which mediates access to the table `me`.
    fn me(&self) -> MeTableHandle<'_>;
}

impl MeTableAccess for super::RemoteTables {
    fn me(&self) -> MeTableHandle<'_> {
        MeTableHandle {
            imp: self.imp.get_table::<Me>("me"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MeInsertCallbackId(__sdk::CallbackId);
pub struct MeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MeTableHandle<'ctx> {
    type Row = Me;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Me> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MeInsertCallbackId {
        MeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MeDeleteCallbackId {
        MeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Me>("me");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Me>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Me>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Me`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait meQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Me`.
    fn me(&self) -> __sdk::__query_builder::Table<Me>;
}

impl meQueryTableAccess for __sdk::QueryTableAccessor {
    fn me(&self) -> __sdk::__query_builder::Table<Me> {
        __sdk::__query_builder::Table::new("me")
    }
}
