// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::user_details_type::UserDetails;
use super::user_type::User;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Me {
    pub user: User,
    pub details: UserDetails,
}

impl __sdk::InModule for Me {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Me`.
///
/// Provides typed access to columns for query building.
pub struct MeCols {
    pub user: __sdk::__query_builder::Col<Me, User>,
    pub details: __sdk::__query_builder::Col<Me, UserDetails>,
}

impl __sdk::__query_builder::HasCols for Me {
    type Cols = MeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MeCols {
            user: __sdk::__query_builder::Col::new(table_name, "user"),
            details: __sdk::__query_builder::Col::new(table_name, "details"),
        }
    }
}
