// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::old_user_type::OldUser;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MigrateUserElevatedArgs {
    pub user: OldUser,
}

impl From<MigrateUserElevatedArgs> for super::Reducer {
    fn from(args: MigrateUserElevatedArgs) -> Self {
        Self::MigrateUserElevated { user: args.user }
    }
}

impl __sdk::InModule for MigrateUserElevatedArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `migrate_user_elevated`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait migrate_user_elevated {
    /// Request that the remote module invoke the reducer `migrate_user_elevated` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`migrate_user_elevated:migrate_user_elevated_then`] to run a callback after the reducer completes.
    fn migrate_user_elevated(&self, user: OldUser) -> __sdk::Result<()> {
        self.migrate_user_elevated_then(user, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `migrate_user_elevated` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn migrate_user_elevated_then(
        &self,
        user: OldUser,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl migrate_user_elevated for super::RemoteReducers {
    fn migrate_user_elevated_then(
        &self,
        user: OldUser,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MigrateUserElevatedArgs { user }, callback)
    }
}
