// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod add_dummy_reducer;
pub mod allow_list_type;
pub mod allowlist_table;
pub mod ban_reducer;
pub mod create_or_update_lobby_reducer;
pub mod delete_my_account_reducer;
pub mod disconnect_reducer;
pub mod disconnect_timer_table;
pub mod disconnect_timer_type;
pub mod identity_connected_reducer;
pub mod identity_disconnected_reducer;
pub mod join_lobby_reducer;
pub mod kick_reducer;
pub mod kickstart_perms_reducer;
pub mod leave_lobby_reducer;
pub mod lobby_ban_table;
pub mod lobby_ban_type;
pub mod lobby_join_table;
pub mod lobby_join_type;
pub mod lobby_table;
pub mod lobby_type;
pub mod me_table;
pub mod me_type;
pub mod migrate_user_elevated_reducer;
pub mod my_bans_table;
pub mod my_verify_timer_table;
pub mod old_user_type;
pub mod permissions_type;
pub mod refresh_procedure;
pub mod region_type;
pub mod relic_refinement_type;
pub mod relic_table;
pub mod relic_timer_table;
pub mod relic_timer_type;
pub mod relic_type;
pub mod remove_dummy_reducer;
pub mod rotation_type_type;
pub mod set_username_reducer;
pub mod set_warframe_id_reducer;
pub mod user_details_table;
pub mod user_details_type;
pub mod user_flags_type;
pub mod user_id_table;
pub mod user_id_type;
pub mod user_table;
pub mod user_type;
pub mod verification_table;
pub mod verify_procedure;
pub mod verify_timer_table;
pub mod verify_timer_type;

pub use add_dummy_reducer::add_dummy;
pub use allow_list_type::AllowList;
pub use allowlist_table::*;
pub use ban_reducer::ban;
pub use create_or_update_lobby_reducer::create_or_update_lobby;
pub use delete_my_account_reducer::delete_my_account;
pub use disconnect_reducer::disconnect;
pub use disconnect_timer_table::*;
pub use disconnect_timer_type::DisconnectTimer;
pub use identity_connected_reducer::identity_connected;
pub use identity_disconnected_reducer::identity_disconnected;
pub use join_lobby_reducer::join_lobby;
pub use kick_reducer::kick;
pub use kickstart_perms_reducer::kickstart_perms;
pub use leave_lobby_reducer::leave_lobby;
pub use lobby_ban_table::*;
pub use lobby_ban_type::LobbyBan;
pub use lobby_join_table::*;
pub use lobby_join_type::LobbyJoin;
pub use lobby_table::*;
pub use lobby_type::Lobby;
pub use me_table::*;
pub use me_type::Me;
pub use migrate_user_elevated_reducer::migrate_user_elevated;
pub use my_bans_table::*;
pub use my_verify_timer_table::*;
pub use old_user_type::OldUser;
pub use permissions_type::Permissions;
pub use refresh_procedure::refresh;
pub use region_type::Region;
pub use relic_refinement_type::RelicRefinement;
pub use relic_table::*;
pub use relic_timer_table::*;
pub use relic_timer_type::RelicTimer;
pub use relic_type::Relic;
pub use remove_dummy_reducer::remove_dummy;
pub use rotation_type_type::RotationType;
pub use set_username_reducer::set_username;
pub use set_warframe_id_reducer::set_warframe_id;
pub use user_details_table::*;
pub use user_details_type::UserDetails;
pub use user_flags_type::UserFlags;
pub use user_id_table::*;
pub use user_id_type::UserId;
pub use user_table::*;
pub use user_type::User;
pub use verification_table::*;
pub use verify_procedure::verify;
pub use verify_timer_table::*;
pub use verify_timer_type::VerifyTimer;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddDummy,
    Ban {
        user: u32,
    },
    CreateOrUpdateLobby {
        lobby_size: u8,
        region: Region,
        refinement: RelicRefinement,
        rotation_type: RotationType,
        activity: String,
    },
    DeleteMyAccount,
    Disconnect {
        disconnect_timer: DisconnectTimer,
    },
    IdentityConnected,
    IdentityDisconnected,
    JoinLobby {
        lobby_id: u32,
    },
    Kick {
        user: u32,
    },
    KickstartPerms {
        target: __sdk::Identity,
    },
    LeaveLobby,
    MigrateUserElevated {
        user: OldUser,
    },
    RemoveDummy,
    SetUsername {
        name: String,
    },
    SetWarframeId {
        warframe_id: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddDummy => "add_dummy",
            Reducer::Ban { .. } => "ban",
            Reducer::CreateOrUpdateLobby { .. } => "create_or_update_lobby",
            Reducer::DeleteMyAccount => "delete_my_account",
            Reducer::Disconnect { .. } => "disconnect",
            Reducer::IdentityConnected => "identity_connected",
            Reducer::IdentityDisconnected => "identity_disconnected",
            Reducer::JoinLobby { .. } => "join_lobby",
            Reducer::Kick { .. } => "kick",
            Reducer::KickstartPerms { .. } => "kickstart_perms",
            Reducer::LeaveLobby => "leave_lobby",
            Reducer::MigrateUserElevated { .. } => "migrate_user_elevated",
            Reducer::RemoveDummy => "remove_dummy",
            Reducer::SetUsername { .. } => "set_username",
            Reducer::SetWarframeId { .. } => "set_warframe_id",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AddDummy => __sats::bsatn::to_vec(&add_dummy_reducer::AddDummyArgs {}),
            Reducer::Ban { user } => {
                __sats::bsatn::to_vec(&ban_reducer::BanArgs { user: user.clone() })
            }
            Reducer::CreateOrUpdateLobby {
                lobby_size,
                region,
                refinement,
                rotation_type,
                activity,
            } => __sats::bsatn::to_vec(&create_or_update_lobby_reducer::CreateOrUpdateLobbyArgs {
                lobby_size: lobby_size.clone(),
                region: region.clone(),
                refinement: refinement.clone(),
                rotation_type: rotation_type.clone(),
                activity: activity.clone(),
            }),
            Reducer::DeleteMyAccount => {
                __sats::bsatn::to_vec(&delete_my_account_reducer::DeleteMyAccountArgs {})
            }
            Reducer::Disconnect { disconnect_timer } => {
                __sats::bsatn::to_vec(&disconnect_reducer::DisconnectArgs {
                    disconnect_timer: disconnect_timer.clone(),
                })
            }
            Reducer::IdentityConnected => {
                __sats::bsatn::to_vec(&identity_connected_reducer::IdentityConnectedArgs {})
            }
            Reducer::IdentityDisconnected => {
                __sats::bsatn::to_vec(&identity_disconnected_reducer::IdentityDisconnectedArgs {})
            }
            Reducer::JoinLobby { lobby_id } => {
                __sats::bsatn::to_vec(&join_lobby_reducer::JoinLobbyArgs {
                    lobby_id: lobby_id.clone(),
                })
            }
            Reducer::Kick { user } => {
                __sats::bsatn::to_vec(&kick_reducer::KickArgs { user: user.clone() })
            }
            Reducer::KickstartPerms { target } => {
                __sats::bsatn::to_vec(&kickstart_perms_reducer::KickstartPermsArgs {
                    target: target.clone(),
                })
            }
            Reducer::LeaveLobby => __sats::bsatn::to_vec(&leave_lobby_reducer::LeaveLobbyArgs {}),
            Reducer::MigrateUserElevated { user } => {
                __sats::bsatn::to_vec(&migrate_user_elevated_reducer::MigrateUserElevatedArgs {
                    user: user.clone(),
                })
            }
            Reducer::RemoveDummy => {
                __sats::bsatn::to_vec(&remove_dummy_reducer::RemoveDummyArgs {})
            }
            Reducer::SetUsername { name } => {
                __sats::bsatn::to_vec(&set_username_reducer::SetUsernameArgs { name: name.clone() })
            }
            Reducer::SetWarframeId { warframe_id } => {
                __sats::bsatn::to_vec(&set_warframe_id_reducer::SetWarframeIdArgs {
                    warframe_id: warframe_id.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    allowlist: __sdk::TableUpdate<AllowList>,
    disconnect_timer: __sdk::TableUpdate<DisconnectTimer>,
    lobby: __sdk::TableUpdate<Lobby>,
    lobby_ban: __sdk::TableUpdate<LobbyBan>,
    lobby_join: __sdk::TableUpdate<LobbyJoin>,
    me: __sdk::TableUpdate<Me>,
    my_bans: __sdk::TableUpdate<LobbyBan>,
    my_verify_timer: __sdk::TableUpdate<VerifyTimer>,
    relic: __sdk::TableUpdate<Relic>,
    relic_timer: __sdk::TableUpdate<RelicTimer>,
    user: __sdk::TableUpdate<User>,
    user_details: __sdk::TableUpdate<UserDetails>,
    user_id: __sdk::TableUpdate<UserId>,
    verification: __sdk::TableUpdate<VerifyTimer>,
    verify_timer: __sdk::TableUpdate<VerifyTimer>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "allowlist" => db_update
                    .allowlist
                    .append(allowlist_table::parse_table_update(table_update)?),
                "disconnect_timer" => db_update
                    .disconnect_timer
                    .append(disconnect_timer_table::parse_table_update(table_update)?),
                "lobby" => db_update
                    .lobby
                    .append(lobby_table::parse_table_update(table_update)?),
                "lobby_ban" => db_update
                    .lobby_ban
                    .append(lobby_ban_table::parse_table_update(table_update)?),
                "lobby_join" => db_update
                    .lobby_join
                    .append(lobby_join_table::parse_table_update(table_update)?),
                "me" => db_update
                    .me
                    .append(me_table::parse_table_update(table_update)?),
                "my_bans" => db_update
                    .my_bans
                    .append(my_bans_table::parse_table_update(table_update)?),
                "my_verify_timer" => db_update
                    .my_verify_timer
                    .append(my_verify_timer_table::parse_table_update(table_update)?),
                "relic" => db_update
                    .relic
                    .append(relic_table::parse_table_update(table_update)?),
                "relic_timer" => db_update
                    .relic_timer
                    .append(relic_timer_table::parse_table_update(table_update)?),
                "user" => db_update
                    .user
                    .append(user_table::parse_table_update(table_update)?),
                "user_details" => db_update
                    .user_details
                    .append(user_details_table::parse_table_update(table_update)?),
                "user_id" => db_update
                    .user_id
                    .append(user_id_table::parse_table_update(table_update)?),
                "verification" => db_update
                    .verification
                    .append(verification_table::parse_table_update(table_update)?),
                "verify_timer" => db_update
                    .verify_timer
                    .append(verify_timer_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.allowlist = cache
            .apply_diff_to_table::<AllowList>("allowlist", &self.allowlist)
            .with_updates_by_pk(|row| &row.id);
        diff.disconnect_timer = cache
            .apply_diff_to_table::<DisconnectTimer>("disconnect_timer", &self.disconnect_timer)
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.lobby = cache
            .apply_diff_to_table::<Lobby>("lobby", &self.lobby)
            .with_updates_by_pk(|row| &row.lobby_id);
        diff.lobby_ban = cache.apply_diff_to_table::<LobbyBan>("lobby_ban", &self.lobby_ban);
        diff.lobby_join = cache
            .apply_diff_to_table::<LobbyJoin>("lobby_join", &self.lobby_join)
            .with_updates_by_pk(|row| &row.user_id);
        diff.relic = cache
            .apply_diff_to_table::<Relic>("relic", &self.relic)
            .with_updates_by_pk(|row| &row.relic);
        diff.relic_timer = cache
            .apply_diff_to_table::<RelicTimer>("relic_timer", &self.relic_timer)
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.user = cache
            .apply_diff_to_table::<User>("user", &self.user)
            .with_updates_by_pk(|row| &row.id);
        diff.user_details = cache
            .apply_diff_to_table::<UserDetails>("user_details", &self.user_details)
            .with_updates_by_pk(|row| &row.user_id);
        diff.user_id = cache
            .apply_diff_to_table::<UserId>("user_id", &self.user_id)
            .with_updates_by_pk(|row| &row.identity);
        diff.verify_timer = cache
            .apply_diff_to_table::<VerifyTimer>("verify_timer", &self.verify_timer)
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.me = cache.apply_diff_to_table::<Me>("me", &self.me);
        diff.my_bans = cache.apply_diff_to_table::<LobbyBan>("my_bans", &self.my_bans);
        diff.my_verify_timer =
            cache.apply_diff_to_table::<VerifyTimer>("my_verify_timer", &self.my_verify_timer);
        diff.verification =
            cache.apply_diff_to_table::<VerifyTimer>("verification", &self.verification);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "allowlist" => db_update
                    .allowlist
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "disconnect_timer" => db_update
                    .disconnect_timer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lobby" => db_update
                    .lobby
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lobby_ban" => db_update
                    .lobby_ban
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "lobby_join" => db_update
                    .lobby_join
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "me" => db_update
                    .me
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_bans" => db_update
                    .my_bans
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_verify_timer" => db_update
                    .my_verify_timer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "relic" => db_update
                    .relic
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "relic_timer" => db_update
                    .relic_timer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_details" => db_update
                    .user_details
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_id" => db_update
                    .user_id
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "verification" => db_update
                    .verification
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "verify_timer" => db_update
                    .verify_timer
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "allowlist" => db_update
                    .allowlist
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "disconnect_timer" => db_update
                    .disconnect_timer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lobby" => db_update
                    .lobby
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lobby_ban" => db_update
                    .lobby_ban
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "lobby_join" => db_update
                    .lobby_join
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "me" => db_update
                    .me
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_bans" => db_update
                    .my_bans
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_verify_timer" => db_update
                    .my_verify_timer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "relic" => db_update
                    .relic
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "relic_timer" => db_update
                    .relic_timer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user" => db_update
                    .user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_details" => db_update
                    .user_details
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_id" => db_update
                    .user_id
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "verification" => db_update
                    .verification
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "verify_timer" => db_update
                    .verify_timer
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    allowlist: __sdk::TableAppliedDiff<'r, AllowList>,
    disconnect_timer: __sdk::TableAppliedDiff<'r, DisconnectTimer>,
    lobby: __sdk::TableAppliedDiff<'r, Lobby>,
    lobby_ban: __sdk::TableAppliedDiff<'r, LobbyBan>,
    lobby_join: __sdk::TableAppliedDiff<'r, LobbyJoin>,
    me: __sdk::TableAppliedDiff<'r, Me>,
    my_bans: __sdk::TableAppliedDiff<'r, LobbyBan>,
    my_verify_timer: __sdk::TableAppliedDiff<'r, VerifyTimer>,
    relic: __sdk::TableAppliedDiff<'r, Relic>,
    relic_timer: __sdk::TableAppliedDiff<'r, RelicTimer>,
    user: __sdk::TableAppliedDiff<'r, User>,
    user_details: __sdk::TableAppliedDiff<'r, UserDetails>,
    user_id: __sdk::TableAppliedDiff<'r, UserId>,
    verification: __sdk::TableAppliedDiff<'r, VerifyTimer>,
    verify_timer: __sdk::TableAppliedDiff<'r, VerifyTimer>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AllowList>("allowlist", &self.allowlist, event);
        callbacks.invoke_table_row_callbacks::<DisconnectTimer>(
            "disconnect_timer",
            &self.disconnect_timer,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Lobby>("lobby", &self.lobby, event);
        callbacks.invoke_table_row_callbacks::<LobbyBan>("lobby_ban", &self.lobby_ban, event);
        callbacks.invoke_table_row_callbacks::<LobbyJoin>("lobby_join", &self.lobby_join, event);
        callbacks.invoke_table_row_callbacks::<Me>("me", &self.me, event);
        callbacks.invoke_table_row_callbacks::<LobbyBan>("my_bans", &self.my_bans, event);
        callbacks.invoke_table_row_callbacks::<VerifyTimer>(
            "my_verify_timer",
            &self.my_verify_timer,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Relic>("relic", &self.relic, event);
        callbacks.invoke_table_row_callbacks::<RelicTimer>("relic_timer", &self.relic_timer, event);
        callbacks.invoke_table_row_callbacks::<User>("user", &self.user, event);
        callbacks.invoke_table_row_callbacks::<UserDetails>(
            "user_details",
            &self.user_details,
            event,
        );
        callbacks.invoke_table_row_callbacks::<UserId>("user_id", &self.user_id, event);
        callbacks.invoke_table_row_callbacks::<VerifyTimer>(
            "verification",
            &self.verification,
            event,
        );
        callbacks.invoke_table_row_callbacks::<VerifyTimer>(
            "verify_timer",
            &self.verify_timer,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        allowlist_table::register_table(client_cache);
        disconnect_timer_table::register_table(client_cache);
        lobby_table::register_table(client_cache);
        lobby_ban_table::register_table(client_cache);
        lobby_join_table::register_table(client_cache);
        me_table::register_table(client_cache);
        my_bans_table::register_table(client_cache);
        my_verify_timer_table::register_table(client_cache);
        relic_table::register_table(client_cache);
        relic_timer_table::register_table(client_cache);
        user_table::register_table(client_cache);
        user_details_table::register_table(client_cache);
        user_id_table::register_table(client_cache);
        verification_table::register_table(client_cache);
        verify_timer_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "allowlist",
        "disconnect_timer",
        "lobby",
        "lobby_ban",
        "lobby_join",
        "me",
        "my_bans",
        "my_verify_timer",
        "relic",
        "relic_timer",
        "user",
        "user_details",
        "user_id",
        "verification",
        "verify_timer",
    ];
}
