// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lobby_ban_type::LobbyBan;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_bans`.
///
/// Obtain a handle from the [`MyBansTableAccess::my_bans`] method on [`super::RemoteTables`],
/// like `ctx.db.my_bans()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_bans().on_insert(...)`.
pub struct MyBansTableHandle<'ctx> {
    imp: __sdk::TableHandle<LobbyBan>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_bans`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBansTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBansTableHandle`], which mediates access to the table `my_bans`.
    fn my_bans(&self) -> MyBansTableHandle<'_>;
}

impl MyBansTableAccess for super::RemoteTables {
    fn my_bans(&self) -> MyBansTableHandle<'_> {
        MyBansTableHandle {
            imp: self.imp.get_table::<LobbyBan>("my_bans"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBansInsertCallbackId(__sdk::CallbackId);
pub struct MyBansDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyBansTableHandle<'ctx> {
    type Row = LobbyBan;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LobbyBan> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyBansInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBansInsertCallbackId {
        MyBansInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBansInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBansDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBansDeleteCallbackId {
        MyBansDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBansDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LobbyBan>("my_bans");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LobbyBan>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LobbyBan>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LobbyBan`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_bansQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LobbyBan`.
    fn my_bans(&self) -> __sdk::__query_builder::Table<LobbyBan>;
}

impl my_bansQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_bans(&self) -> __sdk::__query_builder::Table<LobbyBan> {
        __sdk::__query_builder::Table::new("my_bans")
    }
}
