// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::verify_timer_type::VerifyTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_verify_timer`.
///
/// Obtain a handle from the [`MyVerifyTimerTableAccess::my_verify_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.my_verify_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_verify_timer().on_insert(...)`.
pub struct MyVerifyTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<VerifyTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_verify_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyVerifyTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyVerifyTimerTableHandle`], which mediates access to the table `my_verify_timer`.
    fn my_verify_timer(&self) -> MyVerifyTimerTableHandle<'_>;
}

impl MyVerifyTimerTableAccess for super::RemoteTables {
    fn my_verify_timer(&self) -> MyVerifyTimerTableHandle<'_> {
        MyVerifyTimerTableHandle {
            imp: self.imp.get_table::<VerifyTimer>("my_verify_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyVerifyTimerInsertCallbackId(__sdk::CallbackId);
pub struct MyVerifyTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyVerifyTimerTableHandle<'ctx> {
    type Row = VerifyTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VerifyTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyVerifyTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVerifyTimerInsertCallbackId {
        MyVerifyTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyVerifyTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyVerifyTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVerifyTimerDeleteCallbackId {
        MyVerifyTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyVerifyTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VerifyTimer>("my_verify_timer");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VerifyTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VerifyTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VerifyTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_verify_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VerifyTimer`.
    fn my_verify_timer(&self) -> __sdk::__query_builder::Table<VerifyTimer>;
}

impl my_verify_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_verify_timer(&self) -> __sdk::__query_builder::Table<VerifyTimer> {
        __sdk::__query_builder::Table::new("my_verify_timer")
    }
}
