// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::relic_timer_type::RelicTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct RefreshArgs {
    pub timer: RelicTimer,
}

impl __sdk::InModule for RefreshArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `refresh`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait refresh {
    fn refresh(&self, timer: RelicTimer) {
        self.refresh_then(timer, |_, _| {});
    }

    fn refresh_then(
        &self,
        timer: RelicTimer,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl refresh for super::RemoteProcedures {
    fn refresh_then(
        &self,
        timer: RelicTimer,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<(), String>>(
                "refresh",
                RefreshArgs { timer },
                __callback,
            );
    }
}
