// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relic_timer_type::RelicTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `relic_timer`.
///
/// Obtain a handle from the [`RelicTimerTableAccess::relic_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.relic_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relic_timer().on_insert(...)`.
pub struct RelicTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelicTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `relic_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RelicTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RelicTimerTableHandle`], which mediates access to the table `relic_timer`.
    fn relic_timer(&self) -> RelicTimerTableHandle<'_>;
}

impl RelicTimerTableAccess for super::RemoteTables {
    fn relic_timer(&self) -> RelicTimerTableHandle<'_> {
        RelicTimerTableHandle {
            imp: self.imp.get_table::<RelicTimer>("relic_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RelicTimerInsertCallbackId(__sdk::CallbackId);
pub struct RelicTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RelicTimerTableHandle<'ctx> {
    type Row = RelicTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelicTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RelicTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelicTimerInsertCallbackId {
        RelicTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RelicTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RelicTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelicTimerDeleteCallbackId {
        RelicTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RelicTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RelicTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RelicTimerTableHandle<'ctx> {
    type UpdateCallbackId = RelicTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RelicTimerUpdateCallbackId {
        RelicTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RelicTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `relic_timer`,
/// which allows point queries on the field of the same name
/// via the [`RelicTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relic_timer().scheduled_id().find(...)`.
pub struct RelicTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RelicTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RelicTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `relic_timer`.
    pub fn scheduled_id(&self) -> RelicTimerScheduledIdUnique<'ctx> {
        RelicTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RelicTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RelicTimer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RelicTimer>("relic_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelicTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelicTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelicTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait relic_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelicTimer`.
    fn relic_timer(&self) -> __sdk::__query_builder::Table<RelicTimer>;
}

impl relic_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn relic_timer(&self) -> __sdk::__query_builder::Table<RelicTimer> {
        __sdk::__query_builder::Table::new("relic_timer")
    }
}
