// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Relic {
    pub relic: String,
}

impl __sdk::InModule for Relic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Relic`.
///
/// Provides typed access to columns for query building.
pub struct RelicCols {
    pub relic: __sdk::__query_builder::Col<Relic, String>,
}

impl __sdk::__query_builder::HasCols for Relic {
    type Cols = RelicCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RelicCols {
            relic: __sdk::__query_builder::Col::new(table_name, "relic"),
        }
    }
}

/// Indexed column accessor struct for the table `Relic`.
///
/// Provides typed access to indexed columns for query building.
pub struct RelicIxCols {
    pub relic: __sdk::__query_builder::IxCol<Relic, String>,
}

impl __sdk::__query_builder::HasIxCols for Relic {
    type IxCols = RelicIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RelicIxCols {
            relic: __sdk::__query_builder::IxCol::new(table_name, "relic"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Relic {}
