// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relic_type::Relic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `relic`.
///
/// Obtain a handle from the [`RelicTableAccess::relic`] method on [`super::RemoteTables`],
/// like `ctx.db.relic()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relic().on_insert(...)`.
pub struct RelicTableHandle<'ctx> {
    imp: __sdk::TableHandle<Relic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `relic`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RelicTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RelicTableHandle`], which mediates access to the table `relic`.
    fn relic(&self) -> RelicTableHandle<'_>;
}

impl RelicTableAccess for super::RemoteTables {
    fn relic(&self) -> RelicTableHandle<'_> {
        RelicTableHandle {
            imp: self.imp.get_table::<Relic>("relic"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RelicInsertCallbackId(__sdk::CallbackId);
pub struct RelicDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RelicTableHandle<'ctx> {
    type Row = Relic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Relic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RelicInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelicInsertCallbackId {
        RelicInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RelicInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RelicDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelicDeleteCallbackId {
        RelicDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RelicDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RelicUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RelicTableHandle<'ctx> {
    type UpdateCallbackId = RelicUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RelicUpdateCallbackId {
        RelicUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RelicUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `relic` unique index on the table `relic`,
/// which allows point queries on the field of the same name
/// via the [`RelicRelicUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relic().relic().find(...)`.
pub struct RelicRelicUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Relic, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RelicTableHandle<'ctx> {
    /// Get a handle on the `relic` unique index on the table `relic`.
    pub fn relic(&self) -> RelicRelicUnique<'ctx> {
        RelicRelicUnique {
            imp: self.imp.get_unique_constraint::<String>("relic"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RelicRelicUnique<'ctx> {
    /// Find the subscribed row whose `relic` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Relic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Relic>("relic");
    _table.add_unique_constraint::<String>("relic", |row| &row.relic);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Relic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Relic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Relic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait relicQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Relic`.
    fn relic(&self) -> __sdk::__query_builder::Table<Relic>;
}

impl relicQueryTableAccess for __sdk::QueryTableAccessor {
    fn relic(&self) -> __sdk::__query_builder::Table<Relic> {
        __sdk::__query_builder::Table::new("relic")
    }
}
