// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetWarframeIdArgs {
    pub warframe_id: String,
}

impl From<SetWarframeIdArgs> for super::Reducer {
    fn from(args: SetWarframeIdArgs) -> Self {
        Self::SetWarframeId {
            warframe_id: args.warframe_id,
        }
    }
}

impl __sdk::InModule for SetWarframeIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_warframe_id`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_warframe_id {
    /// Request that the remote module invoke the reducer `set_warframe_id` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_warframe_id:set_warframe_id_then`] to run a callback after the reducer completes.
    fn set_warframe_id(&self, warframe_id: String) -> __sdk::Result<()> {
        self.set_warframe_id_then(warframe_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_warframe_id` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_warframe_id_then(
        &self,
        warframe_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_warframe_id for super::RemoteReducers {
    fn set_warframe_id_then(
        &self,
        warframe_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetWarframeIdArgs { warframe_id }, callback)
    }
}
