// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct User {
    pub id: u32,
    pub name: String,
}

impl __sdk::InModule for User {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `User`.
///
/// Provides typed access to columns for query building.
pub struct UserCols {
    pub id: __sdk::__query_builder::Col<User, u32>,
    pub name: __sdk::__query_builder::Col<User, String>,
}

impl __sdk::__query_builder::HasCols for User {
    type Cols = UserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `User`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserIxCols {
    pub id: __sdk::__query_builder::IxCol<User, u32>,
    pub name: __sdk::__query_builder::IxCol<User, String>,
}

impl __sdk::__query_builder::HasIxCols for User {
    type IxCols = UserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for User {}
