// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_id_type::UserId;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_id`.
///
/// Obtain a handle from the [`UserIdTableAccess::user_id`] method on [`super::RemoteTables`],
/// like `ctx.db.user_id()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_id().on_insert(...)`.
pub struct UserIdTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserId>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_id`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserIdTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserIdTableHandle`], which mediates access to the table `user_id`.
    fn user_id(&self) -> UserIdTableHandle<'_>;
}

impl UserIdTableAccess for super::RemoteTables {
    fn user_id(&self) -> UserIdTableHandle<'_> {
        UserIdTableHandle {
            imp: self.imp.get_table::<UserId>("user_id"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserIdInsertCallbackId(__sdk::CallbackId);
pub struct UserIdDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserIdTableHandle<'ctx> {
    type Row = UserId;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserId> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserIdInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserIdInsertCallbackId {
        UserIdInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserIdInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserIdDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserIdDeleteCallbackId {
        UserIdDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserIdDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserIdUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserIdTableHandle<'ctx> {
    type UpdateCallbackId = UserIdUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserIdUpdateCallbackId {
        UserIdUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserIdUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `user_id`,
/// which allows point queries on the field of the same name
/// via the [`UserIdIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_id().identity().find(...)`.
pub struct UserIdIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserId, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserIdTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `user_id`.
    pub fn identity(&self) -> UserIdIdentityUnique<'ctx> {
        UserIdIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserIdIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserId> {
        self.imp.find(col_val)
    }
}

/// Access to the `id` unique index on the table `user_id`,
/// which allows point queries on the field of the same name
/// via the [`UserIdIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_id().id().find(...)`.
pub struct UserIdIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserId, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserIdTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `user_id`.
    pub fn id(&self) -> UserIdIdUnique<'ctx> {
        UserIdIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserIdIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<UserId> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserId>("user_id");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserId>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserId>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserId`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_idQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserId`.
    fn user_id(&self) -> __sdk::__query_builder::Table<UserId>;
}

impl user_idQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_id(&self) -> __sdk::__query_builder::Table<UserId> {
        __sdk::__query_builder::Table::new("user_id")
    }
}
