// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::permissions_type::Permissions;
use super::user_details_type::UserDetails;
use super::user_flags_type::UserFlags;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_details`.
///
/// Obtain a handle from the [`UserDetailsTableAccess::user_details`] method on [`super::RemoteTables`],
/// like `ctx.db.user_details()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_details().on_insert(...)`.
pub struct UserDetailsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserDetails>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_details`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserDetailsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserDetailsTableHandle`], which mediates access to the table `user_details`.
    fn user_details(&self) -> UserDetailsTableHandle<'_>;
}

impl UserDetailsTableAccess for super::RemoteTables {
    fn user_details(&self) -> UserDetailsTableHandle<'_> {
        UserDetailsTableHandle {
            imp: self.imp.get_table::<UserDetails>("user_details"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserDetailsInsertCallbackId(__sdk::CallbackId);
pub struct UserDetailsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserDetailsTableHandle<'ctx> {
    type Row = UserDetails;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserDetails> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserDetailsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserDetailsInsertCallbackId {
        UserDetailsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserDetailsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserDetailsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserDetailsDeleteCallbackId {
        UserDetailsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserDetailsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserDetailsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserDetailsTableHandle<'ctx> {
    type UpdateCallbackId = UserDetailsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserDetailsUpdateCallbackId {
        UserDetailsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserDetailsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `user_id` unique index on the table `user_details`,
/// which allows point queries on the field of the same name
/// via the [`UserDetailsUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_details().user_id().find(...)`.
pub struct UserDetailsUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserDetails, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserDetailsTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `user_details`.
    pub fn user_id(&self) -> UserDetailsUserIdUnique<'ctx> {
        UserDetailsUserIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserDetailsUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<UserDetails> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserDetails>("user_details");
    _table.add_unique_constraint::<u32>("user_id", |row| &row.user_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserDetails>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserDetails>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserDetails`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_detailsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserDetails`.
    fn user_details(&self) -> __sdk::__query_builder::Table<UserDetails>;
}

impl user_detailsQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_details(&self) -> __sdk::__query_builder::Table<UserDetails> {
        __sdk::__query_builder::Table::new("user_details")
    }
}
