// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserId {
    pub identity: __sdk::Identity,
    pub id: u32,
}

impl __sdk::InModule for UserId {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserId`.
///
/// Provides typed access to columns for query building.
pub struct UserIdCols {
    pub identity: __sdk::__query_builder::Col<UserId, __sdk::Identity>,
    pub id: __sdk::__query_builder::Col<UserId, u32>,
}

impl __sdk::__query_builder::HasCols for UserId {
    type Cols = UserIdCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserIdCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            id: __sdk::__query_builder::Col::new(table_name, "id"),
        }
    }
}

/// Indexed column accessor struct for the table `UserId`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserIdIxCols {
    pub id: __sdk::__query_builder::IxCol<UserId, u32>,
    pub identity: __sdk::__query_builder::IxCol<UserId, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UserId {
    type IxCols = UserIdIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserIdIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserId {}
