// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::permissions_type::Permissions;
use super::user_flags_type::UserFlags;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserDetails {
    pub user_id: u32,
    pub flags: UserFlags,
    pub permissions: Permissions,
}

impl __sdk::InModule for UserDetails {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserDetails`.
///
/// Provides typed access to columns for query building.
pub struct UserDetailsCols {
    pub user_id: __sdk::__query_builder::Col<UserDetails, u32>,
    pub flags: __sdk::__query_builder::Col<UserDetails, UserFlags>,
    pub permissions: __sdk::__query_builder::Col<UserDetails, Permissions>,
}

impl __sdk::__query_builder::HasCols for UserDetails {
    type Cols = UserDetailsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserDetailsCols {
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            flags: __sdk::__query_builder::Col::new(table_name, "flags"),
            permissions: __sdk::__query_builder::Col::new(table_name, "permissions"),
        }
    }
}

/// Indexed column accessor struct for the table `UserDetails`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserDetailsIxCols {
    pub user_id: __sdk::__query_builder::IxCol<UserDetails, u32>,
}

impl __sdk::__query_builder::HasIxCols for UserDetails {
    type IxCols = UserDetailsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserDetailsIxCols {
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserDetails {}
