// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::verify_timer_type::VerifyTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct VerifyArgs {
    pub entry: VerifyTimer,
}

impl __sdk::InModule for VerifyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `verify`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait verify {
    fn verify(&self, entry: VerifyTimer) {
        self.verify_then(entry, |_, _| {});
    }

    fn verify_then(
        &self,
        entry: VerifyTimer,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl verify for super::RemoteProcedures {
    fn verify_then(
        &self,
        entry: VerifyTimer,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<(), String>>(
                "verify",
                VerifyArgs { entry },
                __callback,
            );
    }
}
