// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::verify_timer_type::VerifyTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `verify_timer`.
///
/// Obtain a handle from the [`VerifyTimerTableAccess::verify_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.verify_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.verify_timer().on_insert(...)`.
pub struct VerifyTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<VerifyTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `verify_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VerifyTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VerifyTimerTableHandle`], which mediates access to the table `verify_timer`.
    fn verify_timer(&self) -> VerifyTimerTableHandle<'_>;
}

impl VerifyTimerTableAccess for super::RemoteTables {
    fn verify_timer(&self) -> VerifyTimerTableHandle<'_> {
        VerifyTimerTableHandle {
            imp: self.imp.get_table::<VerifyTimer>("verify_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VerifyTimerInsertCallbackId(__sdk::CallbackId);
pub struct VerifyTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VerifyTimerTableHandle<'ctx> {
    type Row = VerifyTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VerifyTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VerifyTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerifyTimerInsertCallbackId {
        VerifyTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VerifyTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VerifyTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerifyTimerDeleteCallbackId {
        VerifyTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VerifyTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VerifyTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VerifyTimerTableHandle<'ctx> {
    type UpdateCallbackId = VerifyTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VerifyTimerUpdateCallbackId {
        VerifyTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VerifyTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `verify_timer`,
/// which allows point queries on the field of the same name
/// via the [`VerifyTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.verify_timer().scheduled_id().find(...)`.
pub struct VerifyTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VerifyTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VerifyTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `verify_timer`.
    pub fn scheduled_id(&self) -> VerifyTimerScheduledIdUnique<'ctx> {
        VerifyTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VerifyTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VerifyTimer> {
        self.imp.find(col_val)
    }
}

/// Access to the `user_id` unique index on the table `verify_timer`,
/// which allows point queries on the field of the same name
/// via the [`VerifyTimerUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.verify_timer().user_id().find(...)`.
pub struct VerifyTimerUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VerifyTimer, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VerifyTimerTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `verify_timer`.
    pub fn user_id(&self) -> VerifyTimerUserIdUnique<'ctx> {
        VerifyTimerUserIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VerifyTimerUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<VerifyTimer> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VerifyTimer>("verify_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
    _table.add_unique_constraint::<u32>("user_id", |row| &row.user_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VerifyTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VerifyTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VerifyTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait verify_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VerifyTimer`.
    fn verify_timer(&self) -> __sdk::__query_builder::Table<VerifyTimer>;
}

impl verify_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn verify_timer(&self) -> __sdk::__query_builder::Table<VerifyTimer> {
        __sdk::__query_builder::Table::new("verify_timer")
    }
}
