// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VerifyTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub user_id: u32,
    pub warframe_id: String,
    pub code: String,
    pub attempts: u8,
}

impl __sdk::InModule for VerifyTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VerifyTimer`.
///
/// Provides typed access to columns for query building.
pub struct VerifyTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<VerifyTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<VerifyTimer, __sdk::ScheduleAt>,
    pub user_id: __sdk::__query_builder::Col<VerifyTimer, u32>,
    pub warframe_id: __sdk::__query_builder::Col<VerifyTimer, String>,
    pub code: __sdk::__query_builder::Col<VerifyTimer, String>,
    pub attempts: __sdk::__query_builder::Col<VerifyTimer, u8>,
}

impl __sdk::__query_builder::HasCols for VerifyTimer {
    type Cols = VerifyTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VerifyTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            warframe_id: __sdk::__query_builder::Col::new(table_name, "warframe_id"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            attempts: __sdk::__query_builder::Col::new(table_name, "attempts"),
        }
    }
}

/// Indexed column accessor struct for the table `VerifyTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct VerifyTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<VerifyTimer, u64>,
    pub user_id: __sdk::__query_builder::IxCol<VerifyTimer, u32>,
}

impl __sdk::__query_builder::HasIxCols for VerifyTimer {
    type IxCols = VerifyTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VerifyTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for VerifyTimer {}
