// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::verify_timer_type::VerifyTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `verification`.
///
/// Obtain a handle from the [`VerificationTableAccess::verification`] method on [`super::RemoteTables`],
/// like `ctx.db.verification()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.verification().on_insert(...)`.
pub struct VerificationTableHandle<'ctx> {
    imp: __sdk::TableHandle<VerifyTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `verification`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VerificationTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VerificationTableHandle`], which mediates access to the table `verification`.
    fn verification(&self) -> VerificationTableHandle<'_>;
}

impl VerificationTableAccess for super::RemoteTables {
    fn verification(&self) -> VerificationTableHandle<'_> {
        VerificationTableHandle {
            imp: self.imp.get_table::<VerifyTimer>("verification"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VerificationInsertCallbackId(__sdk::CallbackId);
pub struct VerificationDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VerificationTableHandle<'ctx> {
    type Row = VerifyTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VerifyTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VerificationInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerificationInsertCallbackId {
        VerificationInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VerificationInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VerificationDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VerificationDeleteCallbackId {
        VerificationDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VerificationDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VerifyTimer>("verification");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VerifyTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VerifyTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VerifyTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait verificationQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VerifyTimer`.
    fn verification(&self) -> __sdk::__query_builder::Table<VerifyTimer>;
}

impl verificationQueryTableAccess for __sdk::QueryTableAccessor {
    fn verification(&self) -> __sdk::__query_builder::Table<VerifyTimer> {
        __sdk::__query_builder::Table::new("verification")
    }
}
